### ISSUE TITLE
release 1.6

### ISSUE THREAD

**Issue by xambroz** [jtpereyda/libdasm#8]
Hello,
there is bunch of commits which made things hopefully better and it is 9 years since the original 1.5 release. Please would you consider switching the version tag and call it a release on github?

Pull request https://github.com/jtpereyda/libdasm/pull/7

Thank you
Michal Ambroz

**Comment by jtpereyda** [comment]
PR #7 merged. Repo tagged with [v1.6](https://github.com/jtpereyda/libdasm/releases/tag/v1.6). Good to go?

**Comment by xambroz** [comment]
Thank you very much - review of libdasm was accepted for Fedora.
